### ISSUE TITLE
Clarify relation between 1.0 / 2.0 / 2.0-forkme

### ISSUE THREAD

**Issue by patcon** [hackfoldr/hackfoldr-2.0#58]
Hello all!

I would be very much appreciative if someone clarify a some of all of these points for me:

1. What are the differences between the 3 repos?
2. Who, if anyone, is actively maintaining each one?
3. Which codebases are actively used by vTaiwan or other groups?
4. Are there any roadmaps for this project?

Thanks very much for your consideration!

**Comment by patcon** [comment]
Ah, I got confused and thought I'd read this README already. But I see part of my answer is there. I would love to talk about de-confusing this arrangement, if anyone is interested :)

First thoughts:
* prefix repo description with "[DEPRECATED]" on this repo, so someone can understand from the org page.
* make forkme repo description match this one aside from the above suggestion (ie. minimize noise)
* consider merging the repos in some way, so that old commits are in a branch like `old-master` (though perhaps history was rewritten when scrubbing...)
* consider pulling all the important things into one active repo, and sunset one completely -- it's a little confusing to see one with the README wiped, but which is still seeing updates for some reason :) If both must still be kept, consider having a full readme and explaining why?
* rename active repo to `hackfoldr-2.0` and unused one to `hackfoldr-2.0-old` or `hackfoldr-2.0-legacy`, which is more obvious

haha sorry, I am happy to submit changes for any of these, if they seem like decent suggestions :)

**Comment by irvin** [comment]
Hi @patcon , 
because this repo is still working as a running instance at http://beta.hackfoldr.org
and some project still use it, so we might not able to just change the repo link (can we?)

**Comment by patcon** [comment]
Thanks for the reply :) No pressure, was just recording my "pains" (using the term lightly) while trying to understand this project, while they were still fresh in my head.

fwiw, I know if might not just be a technical concern, but on the tech side, all git and http endpoints add 301 redirects

**Comment by patcon** [comment]
Might something like this be acceptable for using as repo link? A high-level doc feels like what I was missing :)
http://beta.hackfoldr.org/meta-hackfoldr

**Comment by irvin** [comment]
@patcon this is great, just add it as default link of beta.hackfoldr.org
